### ISSUE TITLE
GetFirstByLowestScoreFromSet Failed on MongoDB version 4.2

### ISSUE THREAD

**Issue by paratoner** [Hangfire-Mongo/Hangfire.Mongo#326]
Project: Asp.net Core Webapi 
.Net : .Net 6
Service registration :  
```
   // Hangfire
            var mongoUrlBuilder = new MongoUrlBuilder(Configuration.GetConnectionString("HangfireConnection"));
            var mongoClient = new MongoClient(mongoUrlBuilder.ToMongoUrl());

            services.AddHangfire(configuration => configuration
                .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                .UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UseMongoStorage(mongoClient, mongoUrlBuilder.DatabaseName,
                    new MongoStorageOptions
                    {
                        
                        ByPassMigration=true,
                        Prefix = "hangfire.mongo",
                        CheckConnection = true,
                        CheckQueuedJobsStrategy=CheckQueuedJobsStrategy.Poll
                        
                    }));

            services.AddHangfireServer(options => { options.Queues = new[] { "default", "RecurringJobQueue" }; });
```

I am using Azure Cosmos MongoDB  Api (MongoDB Version 4.2)
Hangfire fails at startup.

```
Hangfire.Mongo.MongoConnection: Trace: GetFirstByLowestScoreFromSet(recurring-jobs, 0, 1667505926, 1000)

MongoDB.Driver.MongoCommandException: Command find failed: Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: c8ba4045-692e-4718-a531-2a1f9fe2f480; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: c8ba4045-692e-4718-a531-2a1f9fe2f480; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: c8ba4045-692e-4718-a531-2a1f9fe2f480; Reason: (Message: {"Errors":["The index path corresponding to the specified order-by item is excluded."]}
ActivityId: c8ba4045-692e-4718-a531-2a1f9fe2f480, Request URI: /apps/2fdf0f1b-62ce-463a-97d4-d68696e779d8/services/b3fd7b55-7631-406b-b60d-c37b775a2b68/partitions/90f5eda7-c94a-4f4f-9784-85835632c1ef/replicas/133119627073117538s/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.19041 cosmos-netstandard-sdk/3.18.0);););.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAttempt(RetryableReadContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](IClientSessionHandle session, FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass46_0`1.<FindSync>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.FindSync[TProjection](FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at MongoDB.Driver.FilteredMongoCollectionBase`1.FindSync[TProjection](FilterDefinition`1 filter, FindOptions`2 options, CancellationToken cancellationToken)
   at MongoDB.Driver.FindFluent`2.ToCursor(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToList[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoConnection.GetFirstByLowestScoreFromSet(String key, Double fromScore, Double toScore, Int32 count)
   at Hangfire.Server.DelayedJobScheduler.<>c__DisplayClass14_0.<EnqueueNextScheduledJobs>b__0(IStorageConnection connection)
   at Hangfire.Server.DelayedJobScheduler.UseConnectionDistributedLock[T](JobStorage storage, Func`2 action)
   at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
```
Thanks for help

**Comment by gottscj** [comment]
@paratoner,

Please try the "UseCosmosStorage" extension method provided with the library.

I can see the documentation is lacking somewhat on this. I will try to update it ASAP. 

hope this helps.

**Comment by paratoner** [comment]
I added index to Score field on jobGraph table and issue resolved.
hope this helps other users thank you.
