### ISSUE TITLE
A Database Merging Problem

### ISSUE THREAD

**Issue by pughua** [Hangfire-Mongo/Hangfire.Mongo#335]
Hangfire.Mongo:0.7.22

The steps are as follows：
1.There are multiple working containers running on k8s.
2.Some unexpected databases were deleted.

The following error occurred：
`
2022-12-21 03:03:19.5075 INFO Migration failed in Hangfire.Mongo.Migration.Steps.Version13.SumCounters
2022-12-21 03:03:19.5075 INFO    at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.Execute(MongoStorageOptions storageOptions, IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate(MongoBackupStrategy backupStrategy, MongoMigrationStrategy migrationStrategy)
   at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateIfNeeded(MongoStorageOptions storageOptions, IMongoDatabase database)
   at Hangfire.Mongo.MongoStorage..ctor(MongoClient mongoClient, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoStorage..ctor(MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
`

**Comment by gottscj** [comment]
@pughua,

Thanks for posting. 

I'm not sure how replicate this. Are you saying the database was deleted?

Thanks

**Comment by pughua** [comment]
@gottscj 
Yes, the database has been deleted. Mongodb automatic reconstruction.

**Comment by gottscj** [comment]
@pughua,

it seems the data is corrupted or not all data has been reconstructed. Are you expecting the node to run migrations?

**Comment by gottscj** [comment]
closing due to inactivity
